server:
  port: 8465
logging:
  file: /java/C2S_LOGS/provider-ui/provider-ui.log
info:
  component: Provider UI
# The configuration used for UI
c2s:
  provider-ui:
    provider-permissions:
      is-consent-sign-enabled: false
      is-consent-revokee-enabled: false